/*
 * This file was automatically generated by EvoSuite
 * Sun May 14 08:37:14 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEDA;
import Model.Formulas.FormulaEnergia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaEDA_ESTest extends FormulaEDA_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      double double0 = formulaEDA0.calculo(177.66719, 177.66719, (-2829.71032542089), 177.66719);
      assertEquals((-499590.1189912655), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      double double0 = formulaEDA0.calculo((-2032.01), (-2032.01), (-2032.01), 0.0);
      assertEquals(4129064.6401, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      double double0 = formulaEDA0.calculo(1.0, (-1.0), (-1.0), 1.0);
      assertEquals((-1.1), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      String string0 = formulaEDA0.getId();
      assertEquals("EDA", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      double double0 = formulaEDA0.calculo(0.0, 0.0, 0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      FormulaEnergia formulaEnergia0 = formulaEDA0.clone();
      assertNotSame(formulaEDA0, formulaEnergia0);
  }
}
