/*
 * This file was automatically generated by EvoSuite
 * Sun May 14 08:32:42 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEnergia;
import Model.Formulas.FormulaMuon;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaMuon_ESTest extends FormulaMuon_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaMuon formulaMuon0 = new FormulaMuon();
      double double0 = formulaMuon0.calculo((-2167.7099), 1778.66244, 1778.66244, 0.0);
      assertEquals(3161472.365566754, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaMuon formulaMuon0 = new FormulaMuon();
      double double0 = formulaMuon0.calculo(0.0, 0.0, 0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaMuon formulaMuon0 = new FormulaMuon();
      double double0 = formulaMuon0.calculo((-412.421455), (-412.421455), 1841.26736, (-1.0));
      assertEquals((-759791.5851102087), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaMuon formulaMuon0 = new FormulaMuon();
      String string0 = formulaMuon0.getId();
      assertEquals("Muon", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaMuon formulaMuon0 = new FormulaMuon();
      FormulaEnergia formulaEnergia0 = formulaMuon0.clone();
      assertFalse(formulaEnergia0.equals((Object)formulaMuon0));
  }
}
