/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:51:10 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Menu_ESTest extends Menu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Menu menu0 = new Menu(linkedList0);
      menu0.getOpcao();
      menu0.setOpcao(849);
      linkedList0.pollFirst();
      menu0.setOpcao((-1984));
      String string0 = "Menu";
      linkedList0.addLast("Menu");
      menu0.setOpcao(0);
      List<String> list0 = null;
      // Undeclared exception!
      try { 
        menu0.setOpcoes((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Menu menu0 = new Menu(linkedList0);
      menu0.setOpcao(0);
      ArrayList<String> arrayList0 = menu0.getOpcoes();
      menu0.getOpcoes();
      linkedList0.add("v'6rWc'tL@17?f.GB");
      linkedList0.add("Op\u00E7\u00E3o Inv\u00E1lida!!!");
      menu0.setOpcao((-3380));
      menu0.setOpcoes(linkedList0);
      menu0.setOpcoes(arrayList0);
      menu0.getOpcoes();
      menu0.getOpcao();
      // Undeclared exception!
      menu0.executa();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<Integer> linkedList1 = new LinkedList<Integer>();
      Integer integer0 = new Integer((-187));
      linkedList1.add(integer0);
      linkedList0.retainAll(linkedList1);
      linkedList0.add("J:J)0Z");
      Menu menu0 = new Menu(linkedList0);
      menu0.getOpcoes();
      menu0.setOpcoes(linkedList0);
      menu0.getOpcao();
      // Undeclared exception!
      menu0.executa();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Menu menu0 = new Menu(linkedList0);
      menu0.setOpcoes(linkedList0);
      // Undeclared exception!
      menu0.executa();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("sxTm~1D\"faMYR^Hm$");
      linkedList0.listIterator();
      Menu menu0 = new Menu(linkedList0);
      menu0.getOpcao();
      menu0.getOpcoes();
      int int0 = (-4014);
      menu0.setOpcao((-4014));
      menu0.getOpcoes();
      menu0.getOpcao();
      // Undeclared exception!
      menu0.executa();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("[Oa1(_>$S5[DG :F");
      Menu menu0 = new Menu(linkedList0);
      // Undeclared exception!
      menu0.executa();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Menu menu0 = new Menu(linkedList0);
      linkedList0.add("");
      menu0.setOpcao(1);
      ArrayList<String> arrayList0 = menu0.getOpcoes();
      menu0.setOpcoes(arrayList0);
      ArrayList<String> arrayList1 = menu0.getOpcoes();
      menu0.getOpcao();
      linkedList0.add("");
      menu0.setOpcao(1);
      menu0.setOpcao(0);
      menu0.setOpcao(0);
      menu0.setOpcao(0);
      menu0.setOpcoes(arrayList0);
      menu0.setOpcoes(arrayList1);
      menu0.getOpcao();
      menu0.setOpcao((-1473));
      menu0.getOpcao();
      menu0.getOpcao();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<Integer> linkedList1 = new LinkedList<Integer>();
      Integer integer0 = new Integer(0);
      linkedList1.add(integer0);
      linkedList0.removeAll(linkedList1);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      linkedList0.forEach(consumer0);
      int int0 = 2269;
      // Undeclared exception!
      try { 
        linkedList0.set(2269, "");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2269, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      String string0 = "+~,evLv<Tm{CC7:ohY";
      linkedList0.push("+~,evLv<Tm{CC7:ohY");
      linkedList0.add("*Lo&HL2XLd'");
      Menu menu0 = new Menu(linkedList0);
      menu0.setOpcoes(linkedList0);
      menu0.setOpcao(0);
      menu0.setOpcao(0);
      // Undeclared exception!
      menu0.executa();
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      List<String> list0 = null;
      Menu menu0 = null;
      try {
        menu0 = new Menu((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList", e);
      }
  }
}
