/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed May 10 16:58:30 GMT 2023
 */


import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class UI_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "UI"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
    org.evosuite.runtime.util.SystemInUtil.getInstance().initForTestCase(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/diu/Desktop/ATS/TP/ats_maven_default"); 
    java.lang.System.setProperty("user.home", "/home/diu"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "diu"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(UI_ESTest_scaffolding.class.getClassLoader() ,
      "Model.Formulas.FormulaEnergiaSimples",
      "Model.Formulas.FormulaEDP",
      "Model.Formulas.FormulaIberdrola",
      "Model.Exceptions.SmartDeviceAlreadyExistsException",
      "Model.Exceptions.RoomNotExistsException",
      "Model.Formulas.FormulaLuzboa",
      "Model.Pedido",
      "Model.Exceptions.FaturaNotExistsException",
      "UI",
      "Model.Exceptions.SmartDeviceNotExistsException",
      "Model.Exceptions.LinhaException",
      "Model.Exceptions.FornecedorAlreadyExistsException",
      "Model.Exceptions.FornecedorNotExistsException",
      "Model.Exceptions.CasaInteligenteAlreadyExistsException",
      "Model.SmartHouses",
      "Model.Formulas.FormulaEnat",
      "Model.SmartCamera",
      "Model.Formulas.FormulaGalp",
      "Model.Fornecedor",
      "Menu",
      "Model.SmartBulb",
      "Model.SmartSpeaker",
      "Model.Formulas.FormulaMuon",
      "Model.Formulas.FormulaGoldEnergy",
      "Model.Formulas.FormulaYIce",
      "Model.Formulas.FormulaEndesa",
      "Model.Exceptions.LogAlreadyExistsException",
      "Model.SmartBulb$Mode",
      "Model.CasaInteligente",
      "Model.Formulas.FormulaMEO",
      "Model.Exceptions.CasaInteligenteNotExistsException",
      "Model.Fatura",
      "Model.Formulas.FormulaSUElectricidade",
      "Model.Log",
      "Model.Formulas.FormulaEDA",
      "Model.SmartDevice",
      "Model.Formulas.FormulaCoopernico",
      "Model.Exceptions.LogNotExistsException",
      "Model.Formulas.FormulaEnergia"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(UI_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "UI",
      "Model.SmartHouses",
      "Model.Formulas.FormulaEDP",
      "Model.Formulas.FormulaGalp",
      "Model.Formulas.FormulaIberdrola",
      "Model.Formulas.FormulaEndesa",
      "Model.Formulas.FormulaGoldEnergy",
      "Model.Formulas.FormulaCoopernico",
      "Model.Formulas.FormulaEnat",
      "Model.Formulas.FormulaYIce",
      "Model.Formulas.FormulaMEO",
      "Model.Formulas.FormulaMuon",
      "Model.Formulas.FormulaLuzboa",
      "Model.Formulas.FormulaEnergiaSimples",
      "Model.Formulas.FormulaSUElectricidade",
      "Model.Formulas.FormulaEDA",
      "Model.Fornecedor",
      "Model.Pedido",
      "Model.Exceptions.FornecedorNotExistsException",
      "Model.SmartDevice",
      "Model.SmartBulb",
      "Menu",
      "Model.SmartCamera",
      "Model.Log",
      "Model.SmartSpeaker",
      "Model.CasaInteligente",
      "Model.Exceptions.CasaInteligenteNotExistsException",
      "Model.Exceptions.SmartDeviceNotExistsException",
      "Model.Exceptions.FaturaNotExistsException"
    );
  }
}
