/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:58:30 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Model.CasaInteligente;
import Model.Formulas.FormulaEDA;
import Model.Formulas.FormulaMEO;
import Model.Fornecedor;
import Model.Pedido;
import Model.SmartCamera;
import Model.SmartDevice;
import Model.SmartHouses;
import java.time.Clock;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.HashMap;
import java.util.InputMismatchException;
import java.util.Map;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UI_ESTest extends UI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.executaListPedidos((-1298));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine(":V6~]Br");
      SystemInUtil.addInputLine(":V6~]Br");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.executaDados((-948));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("7h$7&I6C`(Rwx^iVd");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.executaDados(1);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.automatizar("Y6 ld51XlY2LG+#2B");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.volSpk("yiZBp<e`5,5O*3r=F");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("9:V6]Br");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.volSpk("9:V6]Br");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.tonBulb("Model.Exceptions.SmartDeviceAlreadyExistsException");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("m_!H2&F?");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.tonBulb((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("COLD", false);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FormulaMEO formulaMEO0 = new FormulaMEO();
      Fornecedor fornecedor0 = new Fornecedor((-2618.3389), "", formulaMEO0);
      Map<String, CasaInteligente> map0 = fornecedor0.getAllCasas();
      HashMap<String, SmartDevice> hashMap0 = new HashMap<String, SmartDevice>();
      HashMap<String, Fornecedor> hashMap1 = new HashMap<String, Fornecedor>();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      Clock clock0 = MockClock.tickMinutes(zoneOffset0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      SmartHouses smartHouses0 = new SmartHouses(map0, hashMap0, hashMap1, localDateTime0);
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeFornecedores();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeDispositivo("R}trtid|nz9.l]=");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeCasas("NIF: ");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("NF:");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeCasas("NF:");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.ligaDesliga((String) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SystemInUtil.addInputLine("_$*c3GB!3YGzl(c^?");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.ligaDesliga("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.geraDispositivos(787, "");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.geraCasas("NIF");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.executeMenu();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.executaPedido((Pedido) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("UI", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.consultaDispositivos("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SystemInUtil.addInputLine("79N!gLLz,:djF!d<");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.consultaDispositivos("79N!gLLz,:djF!d<");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.consultaCasas();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.automatizar((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaSpeaker("|M=xI");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SystemInUtil.addInputLine("b`G7wnoM$Dr_GI");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaSpeaker("b`G7wnoM$Dr_GI");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaFornecedores();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SystemInUtil.addInputLine("Y_ ld51dQSY2LG+#2B");
      SystemInUtil.addInputLine("Y_ ld51dQSY2LG+#2B");
      SystemInUtil.addInputLine("Y_ ld51dQSY2LG+#2B");
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("Y_ ld51dQSY2LG+#2B");
      SystemInUtil.addInputLine("Y_ ld51dQSY2LG+#2B");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaCasas("");
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaCamera("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      SystemInUtil.addInputLine(";");
      // Undeclared exception!
      try { 
        uI0.adicionaCamera(";");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SystemInUtil.addInputLine("Y_ ld51dQSY2LG+#2B");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaBulb("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.Fornecedores();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.Dispositivos("g,c,2&R&`2A");
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      UI uI0 = null;
      try {
        uI0 = new UI((SmartHouses) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      FormulaEDA formulaEDA0 = new FormulaEDA();
      Fornecedor fornecedor0 = new Fornecedor(328.7807, "", formulaEDA0);
      smartHouses0.adicionaFornecedor("fY|j)P9rW,8seTa#T", fornecedor0);
      smartHouses0.addFornecedor(fornecedor0);
      UI uI0 = null;
      try {
        uI0 = new UI(smartHouses0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Duplicate key Id: ; Imposto: 328.7807;
         //
         verifyException("java.util.stream.Collectors", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.executaListPedidos(0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("8cNIF: ");
      Fornecedor fornecedor0 = new Fornecedor("8cNIF: ", 4217.51);
      smartHouses0.adicionaFornecedor("8cNIF: ", fornecedor0);
      UI uI0 = new UI(smartHouses0);
      uI0.adicionaFornecedores();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SystemInUtil.addInputLine(":'");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaCasas(":'");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SystemInUtil.addInputLine("$z1/4:");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.consultaCasas();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("y=;{~");
      UI uI0 = new UI(smartHouses0);
      uI0.removeFornecedores();
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("NIF");
      Fornecedor fornecedor0 = new Fornecedor("NIF", 4217.51);
      smartHouses0.adicionaFornecedor("NIF", fornecedor0);
      UI uI0 = new UI(smartHouses0);
      uI0.removeCasas("NIF");
      // Undeclared exception!
      try { 
        uI0.adicionaBulb("Ur");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SystemInUtil.addInputLine("v");
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("v");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeDispositivo("v");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      SystemInUtil.addInputLine("SIM");
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("SIM");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeDispositivo("SIM");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      SystemInUtil.addInputLine("v");
      SystemInUtil.addInputLine("Sim");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeDispositivo("v");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      SystemInUtil.addInputLine("cAgK/f");
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("NIF: ");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaFornecedores();
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      FormulaMEO formulaMEO0 = new FormulaMEO();
      Fornecedor fornecedor0 = new Fornecedor((-2618.3389), "", formulaMEO0);
      Map<String, CasaInteligente> map0 = fornecedor0.getAllCasas();
      HashMap<String, SmartDevice> hashMap0 = new HashMap<String, SmartDevice>();
      HashMap<String, Fornecedor> hashMap1 = new HashMap<String, Fornecedor>();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      Clock clock0 = MockClock.tickMinutes(zoneOffset0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      SmartHouses smartHouses0 = new SmartHouses(map0, hashMap0, hashMap1, localDateTime0);
      UI uI0 = new UI(smartHouses0);
      Pedido pedido0 = new Pedido(localDateTime0, "", "T]_@D%I~=v", "gWf%3kD!81r5[2;", "T]_@D%I~=v", false);
      uI0.executaPedido(pedido0);
      assertEquals("gWf%3kD!81r5[2;", pedido0.getFuncao());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      SystemInUtil.addInputLine("oN");
      SystemInUtil.addInputLine("oN");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("oN", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      SystemInUtil.addInputLine("kH");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("kH", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.executaListPedidos(1);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("8cNIF: ");
      Fornecedor fornecedor0 = new Fornecedor("8cNIF: ", 4217.51);
      smartHouses0.adicionaFornecedor("8cNIF: ", fornecedor0);
      UI uI0 = new UI(smartHouses0);
      uI0.removeFornecedores();
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      SmartCamera smartCamera0 = new SmartCamera("\n", false, "\"07&`92Zm", 728.71, 728.71);
      ZoneOffset zoneOffset0 = ZoneOffset.UTC;
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond(1L, 0, zoneOffset0);
      // Undeclared exception!
      try { 
        uI0.addDeviceExecute("", "V!2", " n\u00E3o tem a casa ", smartCamera0, localDateTime0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }
}
