/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 16:15:56 GMT 2023
 */

package Model.Tests;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.opentest4j.AssertionFailedError;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FornecedorTest_ESTest extends FornecedorTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.testClone();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.testEquals();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.testSetImposto();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.testSetFormula();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.testGetId();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.testSetId();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.tearDown();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.testConstructor();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      // Undeclared exception!
      try { 
        fornecedorTest0.testGetImposto();
       //  fail("Expecting exception: AssertionFailedError");
       // Unstable assertion
      } catch(AssertionFailedError e) {
         //
         // expected: <2.0> but was: <10.0>
         //
         verifyException("org.junit.jupiter.api.AssertionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      // Undeclared exception!
      try { 
        fornecedorTest0.testToString();
       //  fail("Expecting exception: AssertionFailedError");
       // Unstable assertion
      } catch(AssertionFailedError e) {
         //
         // expected: <Id: EDP; Imposto:10;> but was: <Id: EDP; Imposto: 10.0;Formula: Model.Formulas.FormulaEDP@2;
         // >
         //
         verifyException("org.junit.jupiter.api.AssertionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FornecedorTest fornecedorTest0 = new FornecedorTest();
      fornecedorTest0.setUp();
  }
}
