/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:46:52 GMT 2023
 */

package Model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Model.SmartBulb;
import Model.SmartDevice;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartBulb_ESTest extends SmartBulb_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("Cold", "Cold", true, 111615, 111615);
      smartBulb0.setDimensao(0);
      SmartBulb smartBulb1 = (SmartBulb)smartBulb0.clone();
      smartBulb1.setDimensao(111615);
      boolean boolean0 = smartBulb1.equals(smartBulb0);
      assertEquals(0, smartBulb0.getDimensao());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("jtmol*-+hfsO}^", "jtmol*-+hfsO}^", true, (-2428), (-2428));
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoNeutral();
      smartBulb0.getMode();
      assertEquals((-2428), smartBulb0.getDimensao());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("t5a'}ePjo)SMtR\"", "t5a'}ePjo)SMtR\"", false, 0, 0);
      int int0 = smartBulb0.getDimensao();
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", "mU.P:$A6Aix[", false, (-1092), (-1092));
      int int0 = smartBulb0.getDimensao();
      assertEquals((-1092), int0);
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        SmartBulb.parseSmartBulb((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartBulb", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        SmartBulb.parseSmartBulb("fX+pPDfpE04i$5|{1(");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         verifyException("Model.SmartBulb", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        SmartBulb.fromString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartBulb", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, "fyCN4,", true, (-2523), (-2523));
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      // Undeclared exception!
      try { 
        smartBulb0.equals(smartBulb1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartDevice", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartBulb smartBulb0 = null;
      try {
        smartBulb0 = new SmartBulb("", (String) null, false, (-3460), 1.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartBulb", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartBulb smartBulb0 = null;
      try {
        smartBulb0 = new SmartBulb("", (String) null, 0, (-3192.468559423192));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartBulb", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartBulb smartBulb0 = null;
      try {
        smartBulb0 = new SmartBulb((SmartBulb) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartDevice", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartBulb.fromString("");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartBulb.Mode smartBulb_Mode0 = SmartBulb.fromString("Neutral");
      assertEquals(SmartBulb.Mode.NEUTRAL, smartBulb_Mode0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartBulb.Mode smartBulb_Mode0 = SmartBulb.fromString("Cold");
      assertEquals(SmartBulb.Mode.COLD, smartBulb_Mode0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", "J/", 0, 0);
      double double0 = smartBulb0.calculaCold();
      assertEquals(0, smartBulb0.getDimensao());
      assertEquals(8.8, double0, 0.01);
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\n", "\n", true, (-1), (-1));
      double double0 = smartBulb0.calculaWarm();
      assertEquals(1.8, double0, 0.01);
      assertEquals((-1), smartBulb0.getDimensao());
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", "", 2095, 2095);
      smartBulb0.getMode();
      assertEquals(2095, smartBulb0.getDimensao());
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("gn5", "gn5", (-1805), (-1805));
      double double0 = smartBulb0.calculaNeutral();
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      assertEquals((-1805), smartBulb0.getDimensao());
      assertEquals(3.4, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(".", ".", false, 2688677, 2688677);
      int int0 = smartBulb0.getDimensao();
      assertEquals(2688677, int0);
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("r|o'FG~Huj)8.[/nS", "a&P", (-6073), (-6073));
      SmartBulb smartBulb1 = new SmartBulb("r|o'FG~Huj)8.[/nS", "r|o'FG~Huj)8.[/nS", false, (-1), (-1));
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertFalse(smartBulb1.equals((Object)smartBulb0));
      assertEquals((-1), smartBulb1.getDimensao());
      assertEquals((-6073), smartBulb0.getDimensao());
      assertEquals(3.4, smartBulb1.consumoDiario(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", "", true, 1050, 1050);
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoCold();
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\n", "\n", false, 1081, (-10.451525158458882));
      boolean boolean0 = smartBulb0.equals((Object) null);
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      assertEquals(1081, smartBulb0.getDimensao());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\n", "\n", false, 1081, (-10.451525158458882));
      boolean boolean0 = smartBulb0.equals(smartBulb0);
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      assertTrue(boolean0);
      assertEquals(1081, smartBulb0.getDimensao());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", "", false, 291, 291);
      SmartBulb smartBulb1 = new SmartBulb((String) null, "", false, 291, 291);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(291, smartBulb1.getDimensao());
      assertEquals(3.4, smartBulb1.consumoDiario(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("60z\n", "60z\n", false, (-17), (-17));
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoWarm();
      double double0 = smartBulb0.consumoDiario();
      assertEquals(1.8, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("60z\n", "60z\n", false, (-17), (-17));
      smartBulb0.changetoNeutral();
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoWarm();
      assertEquals(3.4, smartBulb0.calculaNeutral(), 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("jtmol*-+hfsO}^", "jtmol*-+hfsO}^", true, (-2428), (-2428));
      smartBulb0.changetoCold();
      assertEquals(8.8, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoWarm();
      assertEquals(8.8, smartBulb0.calculaCold(), 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("%s2agjZ\u00077G=RQB", "%s2agjZ\u00077G=RQB", true, (-2336), (-2336));
      smartBulb0.changetoNeutral();
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoCold();
      assertEquals(3.4, smartBulb0.calculaNeutral(), 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("Warm", "Warm", 3465, 3465);
      smartBulb0.changetoCold();
      assertTrue(smartBulb0.getModo());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", "", false, 291, 291);
      smartBulb0.changetoCold();
      smartBulb0.changetoNeutral();
      assertTrue(smartBulb0.getModo());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("%s2agjZ\u00077G=RQB", "%s2agjZ\u00077G=RQB", true, (-2336), (-2336));
      smartBulb0.turnOFFlamp();
      assertEquals((-2336), smartBulb0.getDimensao());
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SmartBulb.Mode smartBulb_Mode0 = SmartBulb.fromString("Warm");
      assertEquals(SmartBulb.Mode.WARM, smartBulb_Mode0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("Cold", "Cold", 0, 0.0);
      SmartBulb smartBulb1 = (SmartBulb)smartBulb0.clone();
      assertEquals(0, smartBulb1.getDimensao());
      assertEquals(8.8, smartBulb1.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("60z\n", "60z\n", false, (-17), (-17));
      String string0 = smartBulb0.toString();
      assertEquals("ID: 60z\n\n\tOn: false;\n\tConsumo Base: -17.0;\n\tModo: null; \tDimensao: -17; ", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("%s2agjZ\u00077G=RQB", "%s2agjZ\u00077G=RQB", true, (-2336), (-2336));
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoCold();
      double double0 = smartBulb0.consumoDiario();
      assertEquals(8.8, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\n", "\n", false, 1081, (-10.451525158458882));
      smartBulb0.changetoWarm();
      assertEquals(1.8, smartBulb0.consumoDiario(), 0.01);
      
      smartBulb0.changetoNeutral();
      assertEquals(1.8, smartBulb0.calculaWarm(), 0.01);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\n", "\n", false, 1081, (-10.451525158458882));
      double double0 = smartBulb0.consumoDiario();
      assertEquals(3.4, double0, 0.01);
      assertEquals(1081, smartBulb0.getDimensao());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\n", "\n", false, 1081, (-10.451525158458882));
      SmartDevice smartDevice0 = smartBulb0.clone();
      boolean boolean0 = smartDevice0.equals(smartBulb0);
      assertEquals(3.4, smartDevice0.consumoDiario(), 0.01);
      assertTrue(smartBulb0.equals((Object)smartDevice0));
      assertEquals(1081, smartBulb0.getDimensao());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("r|o'FG~Huj)8.[/nS", "a&P", (-6073), (-6073));
      boolean boolean0 = smartBulb0.equals("r|o'FG~Huj)8.[/nS");
      assertEquals((-6073), smartBulb0.getDimensao());
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("%s2agjZ\u00077G=RQB", "%s2agjZ\u00077G=RQB", true, (-2336), (-2336));
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
      
      SmartBulb.Mode smartBulb_Mode0 = SmartBulb.Mode.NEUTRAL;
      smartBulb0.setMode(smartBulb_Mode0);
      assertEquals((-2336), smartBulb0.getDimensao());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", "", false, 291, 291);
      smartBulb0.turnOnLamp();
      assertEquals(291, smartBulb0.getDimensao());
      assertEquals(3.4, smartBulb0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      // Undeclared exception!
      try { 
        SmartBulb.parseSmartBulb(",,r7,kz`}ZP:|*7");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }
}
