/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:50:49 GMT 2023
 */

package Model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Model.SmartBulb;
import Model.SmartCamera;
import Model.SmartDevice;
import Model.SmartSpeaker;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartDevice_ESTest extends SmartDevice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera("\tConsumo Base: ", "cu\";kRF:beob)0i2qpr", (-579.840408976536), (-579.840408976536));
      String string0 = smartCamera0.toString();
      assertEquals("ID: \tConsumo Base: \n\tOn: false;\n\tConsumo Base: -579.840408976536;\n\tTamanho: -579.840408976536Mb ; \tResolu\u00E7\u00E3o: cu\";kRF:beob)0i2qpr;\n", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera("\tConsumo Base: ", "cu\";kRF:beob)0i2qpr", (-579.840408976536), (-579.840408976536));
      assertFalse(smartCamera0.getModo());
      
      smartCamera0.turnOn();
      boolean boolean0 = smartCamera0.getModo();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, "\tTamanho: ", (-1166), (-154.41316164271));
      smartBulb0.getID();
      assertFalse(smartBulb0.getModo());
      assertEquals((-154.41316164271), smartBulb0.getConsumoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("", 1995, "", (String) null, (-1.0));
      smartSpeaker0.getID();
      assertFalse(smartSpeaker0.getModo());
      assertEquals((-19.95), smartSpeaker0.consumoDiario(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("F0b%3+0(Yp\"u6w#", (-3164), "\tResolu\u00E7\u00E3o: ", "F0b%3+0(Yp\"u6w#", 0.0);
      double double0 = smartSpeaker0.getConsumoBase();
      assertEquals(0.0, double0, 0.01);
      assertFalse(smartSpeaker0.getModo());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("N2V,4?WMenzPt Z", "", true, 1023, 1023);
      double double0 = smartBulb0.getConsumoBase();
      assertEquals(1023.0, double0, 0.01);
      assertTrue(smartBulb0.getModo());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("!0|Z?,?tc]'&Q:%Wi$Z", 0, "", "\tDimensao: ", 0);
      double double0 = smartSpeaker0.consumoDiario();
      assertEquals(0.0, double0, 0.01);
      assertFalse(smartSpeaker0.getModo());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("N2V,4?WMenzPt Z", "", true, 1023, 1023);
      smartBulb0.consumoDiario();
      assertEquals(1023.0, smartBulb0.getConsumoBase(), 0.01);
      assertTrue(smartBulb0.getModo());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("Model.SmartBulb$Mode", (-2269), "e4sur,dp", "Model.SmartBulb$Mode", 8.8);
      double double0 = smartSpeaker0.consumoDiario();
      assertEquals((-199.672), double0, 0.01);
      assertFalse(smartSpeaker0.getModo());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera("", false, "", 0.0, 0.0);
      SmartDevice smartDevice0 = smartCamera0.clone();
      assertEquals(0.0, smartCamera0.getConsumoBase(), 0.01);
      assertEquals(0.0, smartDevice0.getConsumoBase(), 0.01);
      assertFalse(smartDevice0.getModo());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker((String) null, 312, "^ggC(Q^>R", (String) null, 312);
      SmartDevice smartDevice0 = smartSpeaker0.clone();
      assertEquals(312.0, smartSpeaker0.getConsumoBase(), 0.01);
      assertFalse(smartDevice0.getModo());
      assertEquals(312.0, smartDevice0.getConsumoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\tConsumo Base: ", "\tConsumo Base: ", true, 5578, (-2274.437));
      SmartDevice smartDevice0 = smartBulb0.clone();
      assertTrue(smartDevice0.getModo());
      assertEquals((-2274.437), smartDevice0.getConsumoBase(), 0.01);
      assertEquals((-2274.437), smartBulb0.getConsumoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, "}Q>I_1", true, 1675, 1675);
      SmartBulb smartBulb1 = new SmartBulb("}Q>I_1", "}Q>I_1", (-49), 1675);
      // Undeclared exception!
      try { 
        smartBulb0.equals(smartBulb1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera("", false, "", 0.0, 0.0);
      // Undeclared exception!
      try { 
        smartCamera0.consumoDiario();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera("jyLdz!r)>',kbx", "jyLdz!r)>',kbx", 0.0, 0.0);
      // Undeclared exception!
      try { 
        smartCamera0.consumoDiario();
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"yLdz!r)>',kb\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera((String) null, (String) null, 0.7, 0.0);
      // Undeclared exception!
      try { 
        smartCamera0.consumoDiario();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartCamera", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera("\tConsumo Base: ", "cu\";kRF:beob)0i2qpr", (-579.840408976536), (-579.840408976536));
      boolean boolean0 = smartCamera0.getModo();
      assertFalse(boolean0);
      assertEquals((-579.840408976536), smartCamera0.getConsumoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("\tConsumo Base: ", "\tConsumo Base: ", true, 5578, (-2274.437));
      smartBulb0.getID();
      assertTrue(smartBulb0.getModo());
      assertEquals((-2274.437), smartBulb0.getConsumoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("#n,fvF7`", "A{kDxoR~5P+=g$*I4", false, (-282), (-282));
      double double0 = smartBulb0.getConsumoBase();
      assertEquals((-282.0), double0, 0.01);
      assertFalse(smartBulb0.getModo());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("N2V,4?WMenzPt Z", "", true, 1023, 1023);
      smartBulb0.setConsumoBase(1023);
      assertEquals(1023.0, smartBulb0.getConsumoBase(), 0.01);
      assertTrue(smartBulb0.getModo());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("FaDl.Sart12YzvjOce", "FaDl.Sart12YzvjOce", 54, 54);
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      smartBulb0.changetoCold();
      smartBulb1.equals(smartBulb0);
      assertTrue(smartBulb0.getModo());
      assertFalse(smartBulb1.getModo());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("gu ^x|\"VlE,V!' v", "gu ^x|\"VlE,V!' v", false, 601, 601);
      smartBulb0.setModo(false);
      assertFalse(smartBulb0.getModo());
      assertEquals(601.0, smartBulb0.getConsumoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("gu ^x|\"VlE,V!' v", "gu ^x|\"VlE,V!' v", false, 601, 601);
      smartBulb0.turnOff();
      assertFalse(smartBulb0.getModo());
      assertEquals(601.0, smartBulb0.getConsumoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("gu ^x|\"VlE,V!' v", "gu ^x|\"VlE,V!' v", false, 601, 601);
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertTrue(boolean0);
      assertEquals(601.0, smartBulb1.getConsumoBase(), 0.01);
      assertEquals(601.0, smartBulb0.getConsumoBase(), 0.01);
      assertFalse(smartBulb1.getModo());
  }
}
