/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 16:16:17 GMT 2023
 */

package Model.Tests;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.opentest4j.AssertionFailedError;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartBulbTest_ESTest extends SmartBulbTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testeClone();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testEquals();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testSetDimensao();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      // Undeclared exception!
      try { 
        smartBulbTest0.testToString();
       //  fail("Expecting exception: AssertionFailedError");
       // Unstable assertion
      } catch(AssertionFailedError e) {
         //
         // expected: <Modo: Neutral; Dimens\u00E3o: 3; Consumo Base: 10.0> but was: <ID: bulb1
         // \tOn: false;
         // \tConsumo Base: 10.0;
         // \tModo: null; \tDimensao: 3; >
         //
         verifyException("org.junit.jupiter.api.AssertionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testChangetoWarm();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testTurnOFFlamp();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testChangetoNeutral();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      // Undeclared exception!
      try { 
        smartBulbTest0.testGetDimensao();
       //  fail("Expecting exception: AssertionFailedError");
       // Unstable assertion
      } catch(AssertionFailedError e) {
         //
         // expected: <5> but was: <3>
         //
         verifyException("org.junit.jupiter.api.AssertionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      // Undeclared exception!
      try { 
        smartBulbTest0.testConsumoDiario();
       //  fail("Expecting exception: AssertionFailedError");
       // Unstable assertion
      } catch(AssertionFailedError e) {
         //
         // expected: <8.8> but was: <3.4>
         //
         verifyException("org.junit.jupiter.api.AssertionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.tearDown();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testTurnOnLamp();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testSetMode();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testChangetoCold();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testConstructor();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.testGetMode();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartBulbTest smartBulbTest0 = new SmartBulbTest();
      smartBulbTest0.setUp();
  }
}
