/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 16:27:25 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Model.CasaInteligente;
import Model.Fornecedor;
import Model.Pedido;
import Model.SmartDevice;
import Model.SmartHouses;
import Model.SmartSpeaker;
import java.nio.file.InvalidPathException;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.InputMismatchException;
import java.util.Map;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UI_ESTest extends UI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("&-Gu'c`oK,BT#`wp,");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      Pedido pedido0 = new Pedido(localDateTime0, ", mode=", "", ", mode=", "", false);
      uI0.executaPedido(pedido0);
      assertEquals("", pedido0.getId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("K:;", 0, "Divis\u00E3o: ", "SmartBulb - Tonalidade\n", 0.7);
      // Undeclared exception!
      try { 
        uI0.addDeviceExecute("/es-RB%)", (String) null, "\"(", smartSpeaker0, (LocalDateTime) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.executaListPedidos((-322));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("\nConsumo: ");
      UI uI0 = new UI(smartHouses0);
      uI0.executaDados(506320411);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.automatizar("");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.volSpk((String) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.volSpk("Casas\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.tonBulb("Xiy:x3~[/vY%");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("Qzuy");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.tonBulb("Qzuy");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("3VC;o$c9|b_>R}zN`P", false);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeFornecedores();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashMap<String, CasaInteligente> hashMap0 = new HashMap<String, CasaInteligente>();
      HashMap<String, SmartDevice> hashMap1 = new HashMap<String, SmartDevice>();
      HashMap<String, Fornecedor> hashMap2 = new HashMap<String, Fornecedor>(3235, 3235);
      SmartHouses smartHouses0 = new SmartHouses(hashMap0, hashMap1, hashMap2, (LocalDateTime) null);
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeDispositivo("2Xx''jO`5}J 4t_");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<String, CasaInteligente> hashMap0 = new HashMap<String, CasaInteligente>();
      CasaInteligente casaInteligente0 = new CasaInteligente("", "", 4, "", "");
      Map<String, SmartDevice> map0 = casaInteligente0.getDevices();
      HashMap<String, Fornecedor> hashMap1 = new HashMap<String, Fornecedor>();
      SmartHouses smartHouses0 = new SmartHouses(hashMap0, map0, hashMap1, (LocalDateTime) null);
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeCasas("c1M\"d");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      SystemInUtil.addInputLine("'ip[lsni^]");
      // Undeclared exception!
      try { 
        uI0.removeCasas("'ip[lsni^]");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.ligaDesliga("Fornecedor j\u00E1 tem essa casa");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SystemInUtil.addInputLine("");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.ligaDesliga("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.executeMenu();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.executaPedido((Pedido) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("UI", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.executaDados(647);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.consultaDispositivos("@nt9z[$vFa&B'l_'H");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.consultaDispositivos("Informa\u00E7\u00F5es gerais do Fornecedor\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.consultaCasas();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.automatizar("Digite o ID da casa a remover: ");
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.automatizar((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaSpeaker((String) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine(".sj");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaSpeaker("Nova data(YYYY-MM-DD HH:MM): ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaFornecedores();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SystemInUtil.addInputLine("1-WARM\n2-COLD\n3-NEUTRAL\nTonalidade->");
      SystemInUtil.addInputLine("Volume: ");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaCasas("");
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaCamera("_d9^Tv6e");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SystemInUtil.addInputLine("&-Gu'c`oK,BT#`wp,");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaCamera("Model.Exceptions.LogAlreadyExistsException");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaBulb("x");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SystemInUtil.addInputLine("EDP Comercial");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaBulb("EDP Comercial");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.Fornecedores();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      UI uI0 = null;
      try {
        uI0 = new UI((SmartHouses) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SystemInUtil.addInputLine("On");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.Fornecedores();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SystemInUtil.addInputLine("Formato daa errado");
      SmartHouses smartHouses0 = new SmartHouses();
      Fornecedor fornecedor0 = new Fornecedor("Formato daa errado", (-219.48896852750278));
      smartHouses0.addFornecedor(fornecedor0);
      UI uI0 = new UI(smartHouses0);
      uI0.adicionaFornecedores();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SystemInUtil.addInputLine("");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaCasas("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("Model.Exceptions.CasaInteligenteNotExistsException");
      UI uI0 = new UI(smartHouses0);
      uI0.consultaCasas();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("Model.Exceptions.CasaInteligenteNotExistsException");
      UI uI0 = new UI(smartHouses0);
      uI0.removeFornecedores();
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      SystemInUtil.addInputLine("Formato data errado");
      SmartHouses smartHouses0 = new SmartHouses();
      Fornecedor fornecedor0 = new Fornecedor("Formato data errado", 0.0);
      smartHouses0.addFornecedor(fornecedor0);
      UI uI0 = new UI(smartHouses0);
      uI0.removeCasas("Formato data errado");
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      SystemInUtil.addInputLine("fNO");
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("fNO");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.removeDispositivo("vE[~R.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.geraCasas("3");
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.geraDispositivos(2092851, "2");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.geraDispositivos(2092851, ", funcao='");
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      SystemInUtil.addInputLine("4");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.Dispositivos("v~7");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      uI0.Dispositivos("3");
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      SystemInUtil.addInputLine("4");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.executeMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.executeMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      SystemInUtil.addInputLine("Formato data errado");
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("Formato data errado");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.adicionaFornecedores();
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      SystemInUtil.addInputLine("v@~7");
      SmartHouses smartHouses0 = new SmartHouses();
      SystemInUtil.addInputLine("v@~7");
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("v@~7", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      SystemInUtil.addInputLine("ON");
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      // Undeclared exception!
      try { 
        uI0.setAllDevicesHome("", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Model.SmartHouses", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      SystemInUtil.addInputLine("Formato data errado");
      SmartHouses smartHouses0 = new SmartHouses();
      Fornecedor fornecedor0 = new Fornecedor("Formato data errado", 0.0);
      smartHouses0.addFornecedor(fornecedor0);
      UI uI0 = new UI(smartHouses0);
      uI0.removeFornecedores();
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.executaListPedidos(0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      SmartHouses smartHouses0 = new SmartHouses();
      UI uI0 = new UI(smartHouses0);
      uI0.executaListPedidos(1);
  }
}
