/*
 * This file was automatically generated by EvoSuite
 * Sun May 14 08:27:39 GMT 2023
 */

package Model.Exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Exceptions.SmartDeviceAlreadyExistsException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartDeviceAlreadyExistsException_ESTest extends SmartDeviceAlreadyExistsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SmartDeviceAlreadyExistsException smartDeviceAlreadyExistsException0 = new SmartDeviceAlreadyExistsException("");
  }
}
