/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:52:27 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEnergia;
import Model.Formulas.FormulaGalp;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaGalp_ESTest extends FormulaGalp_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaGalp formulaGalp0 = new FormulaGalp();
      double double0 = formulaGalp0.calculo((-1853.493499526268), (-3657.498519175), (-1853.493499526268), (-1853.493499526268));
      assertEquals(3429927.1607674304, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaGalp formulaGalp0 = new FormulaGalp();
      double double0 = formulaGalp0.calculo(0.0, 0.0, 0.0, 1.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaGalp formulaGalp0 = new FormulaGalp();
      double double0 = formulaGalp0.calculo(1.0, 1.0, (-1639.6384988), 1.0);
      assertEquals((-1637.6384988), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaGalp formulaGalp0 = new FormulaGalp();
      FormulaEnergia formulaEnergia0 = formulaGalp0.clone();
      assertNotSame(formulaEnergia0, formulaGalp0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaGalp formulaGalp0 = new FormulaGalp();
      String string0 = formulaGalp0.getId();
      assertEquals("Galp", string0);
  }
}
