/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:51:25 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEDP;
import Model.Formulas.FormulaEnergia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaEDP_ESTest extends FormulaEDP_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaEDP formulaEDP0 = new FormulaEDP();
      double double0 = formulaEDP0.calculo((-999.173199), (-999.173199), (-999.173199), 0.0);
      assertEquals((-9.975216472344795E8), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaEDP formulaEDP0 = new FormulaEDP();
      double double0 = formulaEDP0.calculo((-558.49), 2882.979811042768, (-558.49), (-558.49));
      assertEquals(1.7984666935376873E9, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaEDP formulaEDP0 = new FormulaEDP();
      double double0 = formulaEDP0.calculo(0.0, (-2257.265), (-2257.265), (-2257.265));
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaEDP formulaEDP0 = new FormulaEDP();
      String string0 = formulaEDP0.getId();
      assertEquals("EDP", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaEDP formulaEDP0 = new FormulaEDP();
      FormulaEnergia formulaEnergia0 = formulaEDP0.clone();
      assertEquals("EDP", formulaEnergia0.getId());
  }
}
