/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:53:11 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEndesa;
import Model.Formulas.FormulaEnergia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaEndesa_ESTest extends FormulaEndesa_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaEndesa formulaEndesa0 = new FormulaEndesa();
      double double0 = formulaEndesa0.calculo((-2922.10039), (-2922.10039), 0.0, 0.0);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaEndesa formulaEndesa0 = new FormulaEndesa();
      double double0 = formulaEndesa0.calculo(0.0, (-1.0), 0.0, (-1.0));
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaEndesa formulaEndesa0 = new FormulaEndesa();
      double double0 = formulaEndesa0.calculo((-1.0), (-1.0), (-1.0), 1024.39);
      assertEquals((-3073.17), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaEndesa formulaEndesa0 = new FormulaEndesa();
      FormulaEnergia formulaEnergia0 = formulaEndesa0.clone();
      assertNotSame(formulaEndesa0, formulaEnergia0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaEndesa formulaEndesa0 = new FormulaEndesa();
      String string0 = formulaEndesa0.getId();
      assertEquals("Endesa", string0);
  }
}
