/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:53:02 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEnergia;
import Model.Formulas.FormulaYIce;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaYIce_ESTest extends FormulaYIce_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaYIce formulaYIce0 = new FormulaYIce();
      double double0 = formulaYIce0.calculo(1.0, 965.1486581670374, 1.0, 965.1486581670374);
      assertEquals(933443.2296779669, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaYIce formulaYIce0 = new FormulaYIce();
      double double0 = formulaYIce0.calculo(0.0, 0.0, 0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaYIce formulaYIce0 = new FormulaYIce();
      String string0 = formulaYIce0.getId();
      assertEquals("YIce", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaYIce formulaYIce0 = new FormulaYIce();
      double double0 = formulaYIce0.calculo((-729.06655080375), (-494.0), 290.253, 290.253);
      assertEquals((-709997.4711408817), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaYIce formulaYIce0 = new FormulaYIce();
      FormulaEnergia formulaEnergia0 = formulaYIce0.clone();
      assertNotSame(formulaYIce0, formulaEnergia0);
  }
}
