/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:51:21 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEnergia;
import Model.Formulas.FormulaEnergiaSimples;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaEnergiaSimples_ESTest extends FormulaEnergiaSimples_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaEnergiaSimples formulaEnergiaSimples0 = new FormulaEnergiaSimples();
      double double0 = formulaEnergiaSimples0.calculo(712.23512263, 2648.37142569, 2648.37142569, 712.23512263);
      assertEquals(6080.201486272999, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaEnergiaSimples formulaEnergiaSimples0 = new FormulaEnergiaSimples();
      double double0 = formulaEnergiaSimples0.calculo((-2266.0), (-2266.0), (-2266.0), (-1406.80217494718));
      assertEquals((-6938.680217494718), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaEnergiaSimples formulaEnergiaSimples0 = new FormulaEnergiaSimples();
      double double0 = formulaEnergiaSimples0.calculo(0.0, 0.0, 0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaEnergiaSimples formulaEnergiaSimples0 = new FormulaEnergiaSimples();
      double double0 = formulaEnergiaSimples0.calculo(1.0, 1554.595365381, 1.0, 1.0);
      assertEquals(1556.6953653809999, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaEnergiaSimples formulaEnergiaSimples0 = new FormulaEnergiaSimples();
      FormulaEnergia formulaEnergia0 = formulaEnergiaSimples0.clone();
      assertEquals("EnergiaSimples", formulaEnergia0.getId());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FormulaEnergiaSimples formulaEnergiaSimples0 = new FormulaEnergiaSimples();
      String string0 = formulaEnergiaSimples0.getId();
      assertEquals("EnergiaSimples", string0);
  }
}
