/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:52:26 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEnat;
import Model.Formulas.FormulaEnergia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaEnat_ESTest extends FormulaEnat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      double double0 = formulaEnat0.calculo(0.0, 3996.0, 0.0, 3996.0);
      assertEquals(1.5968015E7, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      double double0 = formulaEnat0.calculo(1.0, 0.0, 0.0, 2431.3064925555);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      double double0 = formulaEnat0.calculo((-1.0), (-1.0), (-1.0), (-1.0));
      assertEquals((-2.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      String string0 = formulaEnat0.getId();
      assertEquals("Enat", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      FormulaEnergia formulaEnergia0 = formulaEnat0.clone();
      assertNotSame(formulaEnat0, formulaEnergia0);
  }
}
