/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 16:51:52 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEnergia;
import Model.Formulas.FormulaLuzboa;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaLuzboa_ESTest extends FormulaLuzboa_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaLuzboa formulaLuzboa0 = new FormulaLuzboa();
      double double0 = formulaLuzboa0.calculo(3465.0, 0.0, 3465.0, 0.0);
      assertEquals(1.2006225E7, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaLuzboa formulaLuzboa0 = new FormulaLuzboa();
      double double0 = formulaLuzboa0.calculo(0.0, 0.0, 0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaLuzboa formulaLuzboa0 = new FormulaLuzboa();
      double double0 = formulaLuzboa0.calculo((-1.0), (-1.0), 1571.954157, 0.0);
      assertEquals((-1570.954157), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaLuzboa formulaLuzboa0 = new FormulaLuzboa();
      double double0 = formulaLuzboa0.calculo(10.925985834163285, 10.925985834163285, 10.925985834163285, 10.925985834163285);
      assertEquals(358.1314993450103, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaLuzboa formulaLuzboa0 = new FormulaLuzboa();
      FormulaEnergia formulaEnergia0 = formulaLuzboa0.clone();
      assertEquals("Luzboa", formulaEnergia0.getId());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FormulaLuzboa formulaLuzboa0 = new FormulaLuzboa();
      String string0 = formulaLuzboa0.getId();
      assertEquals("Luzboa", string0);
  }
}
