/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 16:22:09 GMT 2023
 */

package Model.Tests.Test;

import Model.Tests.Scaffolding.FormulaCoopernico_ESTest_scaffolding;
import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaCoopernico;
import Model.Formulas.FormulaEnergia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaCoopernico_ESTest extends FormulaCoopernico_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaCoopernico formulaCoopernico0 = new FormulaCoopernico();
      double double0 = formulaCoopernico0.calculo((-1059.71973), 4228.36938, 0.0, 4228.36938);
      assertEquals(3168.6496500000003, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaCoopernico formulaCoopernico0 = new FormulaCoopernico();
      double double0 = formulaCoopernico0.calculo(1282.50519, 1282.50519, 1.0, 1.0);
      assertEquals(2566.01038, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaCoopernico formulaCoopernico0 = new FormulaCoopernico();
      double double0 = formulaCoopernico0.calculo(0.0, 0.0, (-573.94), 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaCoopernico formulaCoopernico0 = new FormulaCoopernico();
      double double0 = formulaCoopernico0.calculo((-1477.4217906066), (-1477.4217906066), (-1.0), (-1477.4217906066));
      assertEquals((-1477.4217906066), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaCoopernico formulaCoopernico0 = new FormulaCoopernico();
      FormulaEnergia formulaEnergia0 = formulaCoopernico0.clone();
      assertNotSame(formulaCoopernico0, formulaEnergia0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FormulaCoopernico formulaCoopernico0 = new FormulaCoopernico();
      String string0 = formulaCoopernico0.getId();
      assertEquals("Coopernico", string0);
  }
}
