/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 16:25:43 GMT 2023
 */

package Model.Tests.Test;

import Model.Tests.Scaffolding.FormulaEDA_ESTest_scaffolding;
import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEDA;
import Model.Formulas.FormulaEnergia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaEDA_ESTest extends FormulaEDA_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      double double0 = formulaEDA0.calculo(0.0, (-1546.0), 0.0, (-1546.0));
      assertEquals(239011.6, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      double double0 = formulaEDA0.calculo((-1546.0), 0.0, 0.0, (-1546.0));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      double double0 = formulaEDA0.calculo(1.0, (-1.0), (-1.0), 1.0);
      assertEquals((-1.1), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      String string0 = formulaEDA0.getId();
      assertEquals("EDA", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaEDA formulaEDA0 = new FormulaEDA();
      FormulaEnergia formulaEnergia0 = formulaEDA0.clone();
      assertFalse(formulaEnergia0.equals((Object)formulaEDA0));
  }
}
