/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 16:22:47 GMT 2023
 */

package Model.Tests.Test;

import Model.Tests.Scaffolding.SmartDeviceAlreadyExistsException_ESTest_scaffolding;
import org.junit.Test;
import Model.Exceptions.SmartDeviceAlreadyExistsException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartDeviceAlreadyExistsException_ESTest extends SmartDeviceAlreadyExistsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SmartDeviceAlreadyExistsException smartDeviceAlreadyExistsException0 = new SmartDeviceAlreadyExistsException("");
  }
}
