/*
 * This file was automatically generated by EvoSuite
 * Sun May 14 08:31:10 GMT 2023
 */

package Model.Formulas;

import org.junit.Test;
import static org.junit.Assert.*;
import Model.Formulas.FormulaEnat;
import Model.Formulas.FormulaEnergia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormulaEnat_ESTest extends FormulaEnat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      double double0 = formulaEnat0.calculo(62.475161936, 62.475161936, 0.0, 62.475161936);
      assertEquals(3964.621020865423, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      double double0 = formulaEnat0.calculo((-2309.509472623), (-2309.509472623), (-2309.509472623), (-2424.93796));
      assertEquals(5595797.170197848, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      double double0 = formulaEnat0.calculo(1.0, 0.0, 0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      double double0 = formulaEnat0.calculo(0.0, 0.0, 0.0, 0.0);
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      String string0 = formulaEnat0.getId();
      assertEquals("Enat", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FormulaEnat formulaEnat0 = new FormulaEnat();
      FormulaEnergia formulaEnergia0 = formulaEnat0.clone();
      assertNotSame(formulaEnat0, formulaEnergia0);
  }
}
